substitutions:
  friendly_name: Aubess 20A
  name: aubess_20a 

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  comment: Aubess 20A with powermonitoring
  project:
    name: PhPersson.aubess-powermonitoring
    version: "1.0"
bk72xx:
  board: generic-bk7231n-qfn32-tuya
  framework:
    version: dev

# To be able to get logs from the device via serial and api.
logger:
dashboard_import:
  package_import_url: github://PhPersson/esphome-config/aubess-plug.yaml@main
  import_full_config: True

api:
# OTA is required for Over-the-Air updating
ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Set up a wifi access point
  ap:

captive_portal:
improv_serial:
web_server:

button:
  - platform: restart
    name: Restart
debug:
  update_interval: 5s


sensor:
- platform: hlw8012
  model: BL0937
  cf_pin:
    number: P7
    inverted: true
  cf1_pin:
    number: P6
    inverted: true
  sel_pin:
    number: P24
    inverted: true
  current:
    name: BL0937 Current
  voltage:
    name: BL0937 Voltage
  power:
    name: BL0937 Power
  energy:
    name: BL0937 Energy
  voltage_divider: 1600
  initial_mode: CURRENT
  current_resistor: 0.001 ohm


binary_sensor:
- platform: gpio
  id: binary_relay
  pin:
    number: P23
    inverted: true
    mode: INPUT_PULLUP
  on_press:
    then:
    - switch.toggle: relay

switch:
  - platform: gpio
    id: relay
    name: Relay
    pin: P26
    on_turn_on:
    - output.turn_on: status_led
    on_turn_off:
      - output.turn_off: status_led

# Setup of LED's used in displaying Switch status
output:
  - platform: gpio
    pin: P8
    inverted: true
    id: status_led
