esphome:
  name: esp32-s2-init
  friendly_name: ESP32-S2-init
  comment: ESP32-S2-init
  platformio_options:
    board_build.flash_mode: dio
    board_build.f_cpu: 80000000L
    board_build.extra_flags:
      - "-DARDUINO_USB_CDC_ON_BOOT=0"

esp32:
  board: lolin_s2_mini
  framework:
    type: arduino

improv_serial:

logger:
  hardware_uart: uart0

# Enable Home Assistant API
api:

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap: {}

captive_portal:
web_server:
status_led:
  pin: GPIO15