esphome:
  name: pipe_temp_sensor
  friendly_name: Pipe Temperature Sensor
  comment: Wemos D1 mini with DS18B20
  project:
    name: PhPersson.Pipe_temperature_sensor
    version: "1.0"

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
ota:
  platform: esphome

dashboard_import:
  package_import_url: github://PhPersson/ESPHome-Config/Pipe_temperature_sensor.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: "password"
captive_portal:
web_server:
  

sensor:
  - platform: dallas_temp
    id: Pipe_Temperature

one_wire:
  - platform: gpio
    pin: GPIO2
