substitutions:
  devicename: relay
  upper_devicename: "Relay"

esphome:
  name: $devicename
  friendly_name: $upper_devicename
  comment: "PSF-B01 Self-Locking Relay"
  project:
    name: PhPersson.PSF-B01-relay
    version: "1.0"

esp8266:
  board: esp01_1m

# Enable logging
logger:
# Enable Home Assistant API
api:
ota:
dashboard_import:
  package_import_url: github://PhPersson/ESPHome-Config/D1-relay-template.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap: {}

captive_portal:
web_server:

switch:
  - platform: gpio
    pin: GPIO12
    name: $upper_devicename
    id: relay

  - platform: template
    id: "${devicename}_template"
    name: $upper_devicename
    lambda: |-
      if (id(relay).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
        - switch.turn_on:
            id: relay
    turn_off_action:

        - switch.turn_off:
            id: relay

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO00
      mode: INPUT_PULLUP
    name: "Button Right"
    on_press:
      then:
        - switch.toggle: relay

status_led:
  pin: GPIO15