substitutions:
  devicename: relay
  upper_devicename: "Relay"

esphome:
  name: $devicename
  friendly_name: $upper_devicename
  comment: "PSF-B01 Self-Locking Relay"

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "4YLr0NwxdPjxWa4GeSEUu6DrXnXUmBFB+AQHId4mJ74="

ota:
  password: "5f70ccd826d74be6796a8f81748ee0c8"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: True
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap: {}

captive_portal:
web_server:


binary_sensor:
  - platform: gpio
    pin:
      number: GPIO00
      mode: INPUT_PULLUP
    name: "Button Right"
    on_press:
      then:
        - switch.toggle: relay

switch:
  - platform: gpio
    pin: GPIO12
    name: $upper_devicename
    id: relay