substitutions:
  devicename: usbrelay
  upper_devicename: "USB-Relay"

esphome:
  name: $devicename
  friendly_name: $upper_devicename
  comment: Sinilink USB relay

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "VBYk5VTUr8nxT1cNLhZ7uv6zeU3mMKt/woklLhy8mNI="

ota:
  password: "bfcf16f04d306831ae957a11f5a13d6d"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.10.142
    gateway: 192.168.10.1
    subnet: 255.255.255.0
  fast_connect: True
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap: {}
captive_portal:

status_led:
  pin:
    number: GPIO16 # Blue LED

switch:
  # Relay
  - platform: gpio
    id: usb_relay
    pin: GPIO5

  # Green LED
  - platform: gpio
    pin: GPIO14
    id: green_led
    inverted: false # start on

  - platform: gpio
    pin: GPIO16
    id: blue_led
    inverted: false # start on 

  # Switch template to link relay and green LED states
  # LED is on when relay is off
  - platform: template
    id: "${devicename}_template"
    name: $upper_devicename
    lambda: |-
      if (id(usb_relay).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
  #      - switch.turn_on:
  #          id: green_led
        - switch.turn_on:
            id: usb_relay
    turn_off_action:
  #      - switch.turn_off:
  #          id: green_led
        - switch.turn_off:
            id: usb_relay

# Button
binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO04
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: "usb_relay"