substitutions:
  device_name: led-strip-controller
  device_description: LED Strip Controller.


esphome:
  name: ${device_name}
  friendly_name: LED Controller
  comment: MagicHome-ZJ-WFMN-C-Single Color LED Controller
  project:
    name: MagicHome.ZJ-WFMN-C-Single-led-controller
    version: "1.0"

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap: {}

captive_portal:
web_server: 
dashboard_import:
  package_import_url: github://PhPersson/ESPHome-Config/templates/Single-Color-template.yaml
output:
  - platform: esp8266_pwm
    id: LED
    pin: GPIO12

light:
  - platform: monochromatic
    name: "LED"
    output: LED
