name: Check File Capitalization

on:
  push: {}

jobs:
  check-capitalization:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check filenames
        run: |
          error=false
          for filename in $(git ls-files); do
            if [[ ${filename:0:1} != "$(tr '[:upper:]' '[:lower:]' <<<"${filename:0:1}")" ]]; then
              if [[ "$filename" =~ ^[A-Z][a-z0-9_-]+ ]]; then
                # Valid filename with capital first letter
              else
                echo "Error: File '$filename' does not start with a valid capital letter."
                error=true
              fi
            fi
          done
          if [ "$error" = true ]; then
            exit 1
          fi

